# -*- coding: utf-8 -*-
"""ANN_regression___.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1P_FXBzCpNhuZ673HeDrcFUffxNjcdsNl
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import sys

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.metrics import mean_absolute_error,  mean_squared_error,r2_score
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline

import torch
import torch.nn as nn

from torch.utils.data import DataLoader ,TensorDataset
# import torch

# powerplant_data = pd.read_csv("https://github.com/vishwa-Ansh/DataLoaders/blob/main/powerplant_data.csv$0")
# print(powerplant_data)
# powerplant_data.shape
# powerplant_data.columns
# powerplant_data.dtypes
# # AT => temperature
# # V => vacuum
# # AP => pressure
# # RH => humidity
# # PE => produced energy

powerplant_data = pd.read_csv(
    "https://raw.githubusercontent.com/vishwa-Ansh/DataLoaders/main/powerplant_data.csv"
)

print(powerplant_data)
print(powerplant_data.shape)
print(powerplant_data.columns)
print(powerplant_data.dtypes)

powerplant_data.isnull().sum()

X = powerplant_data.drop('PE', axis=1, inplace=False)
y = powerplant_data['PE']

X_train ,  X_test, y_train, y_test = train_test_split(X, y , test_size=0.2, random_state=42)

scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

np.set_printoptions(threshold=100)
print(X_train_scaled)
print(X_test_scaled)

X_train_tensor = torch.tensor(X_train_scaled, dtype = torch.float32)
X_test_tensor =  torch.tensor(X_test_scaled, dtype = torch.float32)

y_train_tensor = torch.tensor(y_train.values, dtype = torch.float32 ).view(-1,1)
y_test_tensor = torch.tensor(y_test.values, dtype = torch.float32 ).reshape(-1,1)

train_dataset = TensorDataset(X_train_tensor, y_train_tensor)
test_dataset = TensorDataset(X_test_tensor, y_test_tensor)

train_loader = DataLoader(train_dataset, batch_size=32,shuffle=True )
test_loader = DataLoader(test_dataset, batch_size=32)

# class Artifficial_Neural_network(nn.Module):
#     def __init__(self):
#         super(Artifficial_Neural_network , self).__init__()

#         self.model = nn.Sequential(
#             # 1 hidden  layers
#             nn.Linear(in_features = X_test_tensor.shape[1],out_features=64),
#             nn.ReLU(),

#             # 2nd Hidden_layers
#             nn.Linear(in_features=64, out_features=32),
#             nn.ReLU(), # activations functions apply on hidden layers
#             nn.Linear(in_features=32, out_features=16),
#             nn.ReLU(),#out layers
#             nn.Linear(16,1)
#         )

#     def forward(self, x):
#         return self.model(x)


class Artifficial_Neural_network(nn.Module):
    def __init__(self):
        super(Artifficial_Neural_network , self).__init__()

        self.model = nn.Sequential(
            # 1 hidden  layers
            nn.Linear(in_features = X_test_tensor.shape[1],out_features=128),
            nn.ReLU(),
            nn.Linear(in_features=128, out_features=64),
            nn.ReLU(),

            # 2nd Hidden_layers
            nn.Linear(in_features=64, out_features=32),
            nn.ReLU(), # activations functions apply on hidden layers
            nn.Linear(in_features=32, out_features=16),
            nn.ReLU(),#out layers
            nn.Linear(16,1)
        )

    def forward(self, x):
        return self.model(x)

model = Artifficial_Neural_network()
# loss optimizers
crietrion = nn.MSELoss()
optimizer = torch.optim.Adam(model.parameters())

# trianing of Artifficial  neural networks
train_losses = []
val_losses = []

best_val_loss = float("inf")

epochs = 100

for epoch in range(epochs):
    model.train()
    running_loss = 0.0 # tot training loss for 1 epoch

    for xb, yb in train_loader:
        # xb = features of 1 batch
        # yb = labels of 1 batch
        optimizer.zero_grad()

        outputs = model(xb) # forward prop....predicted outputs for this batch
        loss = crietrion(outputs, yb) # compute loss
        loss.backward() # back prop.. compute gradients
        optimizer.step() # params update

        running_loss += loss.item() # loss is a tensor => py float

    epoch_train_loss = running_loss / len(train_loader)
    train_losses.append(epoch_train_loss)


    # Validation
    model.eval()
    running_val_loss = 0.0

    with torch.no_grad(): # no gradients compute
        for xb, yb in test_loader:
            outputs = model(xb)
            loss = crietrion(outputs, yb)
            running_val_loss += loss

    epoch_val_loss = running_val_loss / len(test_loader)
    val_losses.append(epoch_val_loss)

    print(f"epoch {epoch+1}/{epochs} ==> train loss = {epoch_train_loss} & val loss = {epoch_val_loss}")

    if epoch_val_loss < best_val_loss:
        best_val_loss = epoch_val_loss
        torch.save(model.state_dict(), "best_model.pt") #.pt or .pth

loss_df = pd.DataFrame({
    "Training Loss": train_losses,
    "Validation Loss": val_losses
})
plt.figure(figsize=(15, 5))

plt.plot(loss_df["Training Loss"], label = "Training Loss")
plt.plot(loss_df["Validation Loss"], label = "Validation Loss")

plt.xlabel("Epochs")
plt.ylabel("Losses")

plt.legend()
# Loading the best model

model.load_state_dict(
    torch.load(
        "best_model.pt",
        map_location="cpu",
        weights_only=True
    )
)
# model.eval()
# with torch.no_grad():
#     train_preds = model(X_train_tensor)
#     test_preds = model(X_test_tensor)

#     train_mse_loss = crietrion(train_preds, y_train_tensor)
#     test_mse_loss = crietrion(test_preds, y_test_tensor)

# print("Training MSE:", train_mse_loss.item())
# print("Testing MSE:", test_mse_loss.item())

# print("r^2 score =", r2_score(y_test, test_preds))

# predicted_df = pd.DataFrame(test_preds.numpy(), columns=["Predicted Values"])
# actual_df = pd.DataFrame(y_test.values, columns=["Actual Values"])

# pd.concat([predicted_df, actual_df], axis=1)

model.eval()

with torch.no_grad():
    train_preds = model(X_train_tensor)
    test_preds = model(X_test_tensor)

train_mse_loss = crietrion(train_preds, y_train_tensor)
test_mse_loss = crietrion(test_preds, y_test_tensor)

print("Training MSE:", train_mse_loss.item())
print("Testing MSE:", test_mse_loss.item())

train_preds_np = train_preds.detach().cpu().numpy().ravel()
test_preds_np = test_preds.detach().cpu().numpy().ravel()

print("R² score =", r2_score(y_test.to_numpy(), test_preds_np))

predicted_df = pd.DataFrame({
    "Predicted Values": test_preds_np
})

actual_df = pd.DataFrame({
    "Actual Values": y_test.to_numpy()
})

result = pd.concat(
    [predicted_df, actual_df],
    axis=1
)

print(result)

for i ,j in zip(np.asarray(predicted_df),np.asarray(actual_df)):
    if int(i) == int(j):
        print("correct")



import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

import torch
import torch.nn as nn

from torch.utils.data import DataLoader, TensorDataset

powerplant_data = pd.read_csv("https://raw.githubusercontent.com/vishwa-Ansh/DataLoaders/main/powerplant_data.csv")

print(powerplant_data)
print(powerplant_data.shape)
print(powerplant_data.columns)
print(powerplant_data.dtypes)

print(powerplant_data.isnull().sum())

X = powerplant_data.drop("PE", axis=1)
y = powerplant_data["PE"]

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

scaler = StandardScaler()

X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

X_train_tensor = torch.tensor(
    X_train_scaled,
    dtype=torch.float32
)

X_test_tensor = torch.tensor(
    X_test_scaled,
    dtype=torch.float32
)

y_train_tensor = torch.tensor(
    y_train.values,
    dtype=torch.float32
).reshape(-1, 1)

y_test_tensor = torch.tensor(
    y_test.values,
    dtype=torch.float32
).reshape(-1, 1)

train_dataset = TensorDataset(
    X_train_tensor,
    y_train_tensor
)

test_dataset = TensorDataset(
    X_test_tensor,
    y_test_tensor
)

train_loader = DataLoader(
    train_dataset,
    batch_size=32,
    shuffle=True
)

test_loader = DataLoader(
    test_dataset,
    batch_size=32
)


class Artificial_Neural_Network(nn.Module):

    def __init__(self):
        super().__init__()

        self.model = nn.Sequential(
            nn.Linear(X_train_tensor.shape[1], 6),
            nn.ReLU(),

            nn.Linear(6, 6),
            nn.ReLU(),

            nn.Linear(6, 1)
        )

    def forward(self, x):
        return self.model(x)


model = Artificial_Neural_Network()

criterion = nn.MSELoss()

optimizer = torch.optim.Adam(
    model.parameters(),
    lr=0.001
)

train_losses = []
val_losses = []

best_val_loss = float("inf")

epochs = 100

for epoch in range(epochs):

    model.train()

    running_loss = 0.0

    for xb, yb in train_loader:

        optimizer.zero_grad()

        outputs = model(xb)

        loss = criterion(outputs, yb)

        loss.backward()

        optimizer.step()

        running_loss += loss.item()

    epoch_train_loss = running_loss / len(train_loader)

    train_losses.append(epoch_train_loss)

    model.eval()

    running_val_loss = 0.0

    with torch.no_grad():

        for xb, yb in test_loader:

            outputs = model(xb)

            loss = criterion(outputs, yb)

            running_val_loss += loss.item()

    epoch_val_loss = running_val_loss / len(test_loader)

    val_losses.append(epoch_val_loss)

    print(
        f"Epoch {epoch + 1}/{epochs} "
        f"==> Train Loss = {epoch_train_loss:.4f} "
        f"| Val Loss = {epoch_val_loss:.4f}"
    )

    if epoch_val_loss < best_val_loss:

        best_val_loss = epoch_val_loss

        torch.save(
            model.state_dict(),
            "best_model.pt"
        )


plt.figure(figsize=(10, 5))

plt.plot(
    train_losses,
    label="Training Loss"
)

plt.plot(
    val_losses,
    label="Validation Loss"
)

plt.xlabel("Epochs")
plt.ylabel("Loss")

plt.legend()

plt.show()


model.load_state_dict(
    torch.load(
        "best_model.pt",
        weights_only=True
    )
)

model.eval()

with torch.no_grad():

    train_preds = model(X_train_tensor)
    test_preds = model(X_test_tensor)


train_mse = mean_squared_error(
    y_train,
    train_preds.numpy().ravel()
)

test_mse = mean_squared_error(
    y_test,
    test_preds.numpy().ravel()
)

train_mae = mean_absolute_error(
    y_train,
    train_preds.numpy().ravel()
)

test_mae = mean_absolute_error(
    y_test,
    test_preds.numpy().ravel()
)

r2 = r2_score(
    y_test,
    test_preds.numpy().ravel()
)

print("Training MSE:", train_mse)
print("Testing MSE:", test_mse)

print("Training MAE:", train_mae)
print("Testing MAE:", test_mae)

print("R² Score:", r2)


predicted_df = pd.DataFrame(
    test_preds.numpy().ravel(),
    columns=["Predicted Values"]
)

actual_df = pd.DataFrame(
    y_test.values,
    columns=["Actual Values"]
)

result = pd.concat(
    [predicted_df, actual_df],
    axis=1
)

print(result)

