# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colab.

Original file is locat at
    https://colab.research.google.com/drive/1Md0jRgovG5-j3rQvRdiB2P8esJrOzWFO
"""

import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

import torch
import torch.nn as nn

import tensorflow as tf
from torch.utils.data import TensorDataset, DataLoader

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder, OneHotEncoder
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
from sklearn.model_selection import train_test_split

fruit_data = pd.read_csv('https://raw.githubusercontent.com/vishwa-Ansh/DataLoaders/refs/heads/main/Data_fruit.csv')
fruit_data



X = fruit_data.drop('Class', axis=1)
y = fruit_data['Class']


label_encoding  = LabelEncoder()
y = label_encoding.fit_transform(y)

X_train, X_test, y_train , y_test = train_test_split(X, y, test_size=0.2, random_state=42)
print(X_test.shape, y_test.shape)
print(X_train.shape, y_train.shape)

scaler_encoding = StandardScaler()
X_train_scale = scaler_encoding.fit_transform(X_train)
X_test_scale = scaler_encoding.transform(X_test)

X_train_tensor = torch.tensor(X_train_scale, dtype = torch.float32)
X_test_tensor =  torch.tensor(X_test_scale, dtype = torch.float32)

y_train_tensor = torch.tensor(y_train,  dtype = torch.long)
y_test_tensor = torch.tensor(y_test,  dtype=torch.long)
print(X_test_tensor)
print(y_train_tensor)

train_dataset = TensorDataset(X_train_tensor, y_train_tensor)
test_dataset = TensorDataset(X_test_tensor,  y_test_tensor)

train_loader = DataLoader(train_dataset, batch_size=32, shuffle=True)
test_loader = DataLoader(test_dataset, batch_size = 32, shuffle= False)

y_train

X_train = np.asarray(X_train_scale, dtype=np.float32)
X_test = np.asarray(X_test_scale, dtype=np.float32)

y_train = np.asarray(y_train, dtype=np.int32)
y_test = np.asarray(y_test, dtype=np.int32)

model = tf.keras.Sequential([
    tf.keras.layers.Input(
        shape=(X_train.shape[1],)
    ),

    tf.keras.layers.Dense(32),
    tf.keras.layers.ReLU(),

    tf.keras.layers.Dense(32),
    tf.keras.layers.ReLU(),

    tf.keras.layers.Dense(7)
])

model.compile(
    optimizer=tf.keras.optimizers.Adam(
         learning_rate=0.001
    ),
    loss=tf.keras.losses.SparseCategoricalCrossentropy(
        from_logits=True
    ),
    metrics=["accuracy"]
)

model.summary()

history = model.fit(
    X_train,
    y_train,
    epochs=100,
    batch_size=32,
    validation_split=0.2,
    verbose=1
)

loss, accuracy = model.evaluate(
    X_test,
    y_test
)

print("Test Loss:", loss)
print("Test Accuracy:", accuracy)

logits = model.predict(X_test)

probabilities = tf.nn.softmax(
    logits,
    axis=1
)

print("Probabilities:")
print(probabilities.numpy())

predictions = tf.argmax(
    probabilities,
    axis=1
)

print("Predicted classes:")
print(predictions.numpy())

X_train_tensorflow = np.asarray(X_train_scale, dtype=np.float32)
X_test_tensorflow = np.asarray(X_test_scale, dtype=np.float32
                                )

y_train_tensorflow = np.asarray(y_train, dtype=np.int32)
y_test_tensorflow = np.asarray(y_test, dtype=np.int32)

model = tf.keras.Sequential([
    tf.keras.layers.Input(
        shape=(X_train_tensorflow.shape[1],)
    ),
    tf.keras.layers.Dense(32),
    tf.keras.layers.ReLU(),

    tf.keras.layers.Dense(32),
    tf.keras.layers.ReLU(),

    tf.keras.layers.Dense(7)
])

model.compile(
    optimizer=tf.keras.optimizers.Adam(
         learning_rate=0.001
    ),
    loss=tf.keras.losses.SparseCategoricalCrossentropy(
        from_logits=True
    ),
    metrics=["accuracy"]
)

model.summary()

history = model.fit(
    X_train_tensorflow,
    y_train_tensorflow,
    epochs=100,
    batch_size=32,
    validation_split=0.2,
    verbose=1
)

loss, accuracy = model.evaluate(
    X_test_tensorflow,
    y_test_tensorflow
)

print("Test Loss:", loss)
print("Test Accuracy:", accuracy)

X_train_tensor = torch.tensor(X_train_scale, dtype = torch.float32)
X_test_tensor =  torch.tensor(X_test_scale, dtype = torch.float32)

y_train_tensor = torch.tensor(y_train,  dtype = torch.long)
y_test_tensor = torch.tensor(y_test,  dtype=torch.long)
print(X_test_tensor)
print(y_train_tensor)

trianDataset = TensorDataset(X_train_tensor, y_train_tensor)
testDataset = TensorDataset(X_test_tensor,  y_test_tensor)

train_loader = DataLoader(trianDataset, batch_size=32, shuffle=True)
test_loader = DataLoader(testDataset, batch_size = 32, shuffle= False)

class Artificial_neural_network(nn.Module):
    def __init__(self):
        super(Artificial_neural_network, self).__init__()
        self.input_layer = nn.Linear(X_train_tensor.shape[1], 32)
        self.hidden_layer1 = nn.Linear(32, 32)
        self.output_layer = nn.Linear(32, 7)
        self.relu = nn.ReLU()
    def forward(self, x):
        x = self.input_layer(x)
        x = self.relu(x)
        x = self.hidden_layer1(x)
        x = self.relu(x)
        x = self.output_layer(x)
        return x

epochs = 100
learning_rate = 0.001

model = Artificial_neural_network()
criterion = nn.CrossEntropyLoss()
optimizer = torch.optim.Adam(model.parameters(), lr=learning_rate)

for epoch in range(epochs):
  running_loss = 0.0
  model.train();
  for batch_idx, (data, target) in enumerate(train_loader):
    optimizer.zero_grad()
    output = model(data)
    loss = criterion(output, target)
    loss.backward()
    optimizer.step()
    running_loss += loss.item()
  train_loss = running_loss / len(train_loader)
  print(f"epoch = {epoch+1}/{epochs}, loss = {train_loss}")



model.eval()

total = 0
correct = 0

with torch.no_grad():
    for xb, yb in test_loader:
        outputs = model(xb) # [0.2, 0.5, 1.3, -0.5, ..] - 7 vals
        _values, indices = torch.max(outputs, dim=1)
        print(indices )
        # print(outputs)
        correct += (indices == yb).sum().item()
        total += yb.size(0) # actual samples in each batch

print("accuracy: ", correct/total * 100)
# print(accuracy_score())